source 'https://rubygems.org'

gem 'middleman', '4.4.0'
gem 'middleman-livereload', '3.4.7'
gem 'middleman-syntax', '3.2.0'
gem 'middleman-blog', '4.0.1'

# Middleman has an undeclared dependency on `tzinfo-data` for
# generating timestamps.
#
# TODO(bbannier): Remove this explicit dependency when middleman
# correctly declares its requirements.
gem 'tzinfo-data', '>= 1.2018.6'

gem 'rdiscount', '2.2.0.1'

gem 'htmlentities'

gem 'therubyracer'

gem 'rake'
